plugins {
	id 'dev.architectury.loom' version '1.7-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version + '+' + project.mod_minecraft_version + '.neoforge' + getExtraBuildMetadata()
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

static String getExtraBuildMetadata() {
	String buildNumber = System.getenv('GITHUB_RUN_NUMBER')
	if (buildNumber != null) {
		return ".build.${buildNumber}"
	}
	return ''
}

repositories {
	// Add NeoForged repository.
	maven {
		name = 'NeoForged'
		url = 'https://maven.neoforged.net/releases'
	}

	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.

	maven {
		name 'TerraformersMC'
		url 'https://maven.terraformersmc.com'
	}
	maven {
		name 'Modrinth'
		url 'https://api.modrinth.com/maven'
	}
	maven {
		name 'Shedaniel'
		url 'https://maven.shedaniel.me'
	}
	maven {
		name 'Sinytra'
		url "https://maven.su5ed.dev/releases"
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "net.minecraft:minecraft:$project.minecraft_version"
	mappings loom.layered {
		it.mappings("net.fabricmc:yarn:$project.yarn_mappings:v2")
		it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$project.yarn_mappings_patch_version")
	}
	neoForge "net.neoforged:neoforge:$project.neoforge_version"

	modImplementation include("org.sinytra.forgified-fabric-api:fabric-api-base:+")
	modImplementation include("org.sinytra.forgified-fabric-api:fabric-resource-loader-v0:+")
	modImplementation include("org.sinytra.forgified-fabric-api:fabric-model-loading-api-v1:+")
	modImplementation include("org.sinytra.forgified-fabric-api:fabric-renderer-api-v1:+")
	modImplementation include("org.sinytra.forgified-fabric-api:fabric-block-view-api-v2:+")

	modImplementation include("org.sinytra.forgified-fabric-api:fabric-lifecycle-events-v1:+")
	modImplementation include("org.sinytra.forgified-fabric-api:fabric-networking-api-v1:+")

	modImplementation include("org.sinytra:fabric-loader:+")
}

processResources {
	inputs.property 'version', project.version

	filesMatching('META-INF/neoforge.mods.toml') {
		expand version: project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from('LICENSE') {
		rename { "${it}_${project.base.archivesName.get()}" }
	}
}

// configure the maven publication
publishing {
	publications {
		create('mavenJava', MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
