# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Arch Loom Properties
loom.platform = neoforge
neoforge_version = 21.1.84
yarn_mappings_patch_version = 1.21+build.4

# Fabric Properties
loom_version = 1.7-SNAPSHOT
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.1

# Mod Properties
mod_version = 3.0.0
mod_minecraft_version = 1.21
maven_group = me.pepperbell
archives_base_name = continuity

# Dependencies
fabric_version = 0.104.0+2.0.19+1.21.1
loader_version = 2.6.14+0.15.10+1.21
