# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true
loom.platform = neoforge

# Fabric Properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.1

# Mod Properties
mod_version = 3.0.0
mod_minecraft_version = 1.21
maven_group = me.pepperbell
archives_base_name = continuity

# Dependencies
fabric_version = 0.100.1+1.21
neoforge_version = 21.1.84
yarn_mappings_patch_version = 1.21+build.4
