# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
loom_version = 1.17.11
minecraft_version = 26.2
loader_version = 0.19.3

# Mod Properties
mod_version = 3.0.1
mod_minecraft_version = 26.2
maven_group = me.pepperbell
archives_base_name = continuity

# Dependencies
fabric_version = 0.152.1+26.2
modmenu_version = 20.0.0-beta.2
sodium_version = 0.9.0+mc26.2
